#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'BeaconMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 2

# The Active Message type associated with this message.
AM_TYPE = -1

class BeaconMsg(tinyos.message.Message.Message):
    # Create a new BeaconMsg of size 2.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=2):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <BeaconMsg> \n"
        try:
            s += "  [msg_type=0x%x]\n" % (self.get_msg_type())
        except:
            pass
        try:
            s += "  [hop_count=0x%x]\n" % (self.get_hop_count())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: msg_type
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'msg_type' is signed (False).
    #
    def isSigned_msg_type(self):
        return False
    
    #
    # Return whether the field 'msg_type' is an array (False).
    #
    def isArray_msg_type(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'msg_type'
    #
    def offset_msg_type(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'msg_type'
    #
    def offsetBits_msg_type(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'msg_type'
    #
    def get_msg_type(self):
        return self.getUIntElement(self.offsetBits_msg_type(), 8, 1)
    
    #
    # Set the value of the field 'msg_type'
    #
    def set_msg_type(self, value):
        self.setUIntElement(self.offsetBits_msg_type(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'msg_type'
    #
    def size_msg_type(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'msg_type'
    #
    def sizeBits_msg_type(self):
        return 8
    
    #
    # Accessor methods for field: hop_count
    #   Field type: short
    #   Offset (bits): 8
    #   Size (bits): 8
    #

    #
    # Return whether the field 'hop_count' is signed (False).
    #
    def isSigned_hop_count(self):
        return False
    
    #
    # Return whether the field 'hop_count' is an array (False).
    #
    def isArray_hop_count(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'hop_count'
    #
    def offset_hop_count(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'hop_count'
    #
    def offsetBits_hop_count(self):
        return 8
    
    #
    # Return the value (as a short) of the field 'hop_count'
    #
    def get_hop_count(self):
        return self.getUIntElement(self.offsetBits_hop_count(), 8, 1)
    
    #
    # Set the value of the field 'hop_count'
    #
    def set_hop_count(self, value):
        self.setUIntElement(self.offsetBits_hop_count(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'hop_count'
    #
    def size_hop_count(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'hop_count'
    #
    def sizeBits_hop_count(self):
        return 8
    
