#ifndef GENERAL_MOTION_SESNSORS_H
#define GENERAL_MOTION_SESNSORS_H

enum SensorResponses {
	GMSI_MOVE_DETECTED = 128,
	GMSI_NO_MOVE_DETECTED,
	GMSI_SENSOR_NOT_READY,
	GMSI_ACK,
	GMSI_NACK
};

#endif /* GENERAL_MOTION_SESNSORS_H */
